### PR TITLE
Automatically build against hdf5 from rwinlib (fixes #128)

### LINKED ISSUE #128: Fails to build on Windows with hdf5 1.10.5 from rtools40
Hi, we are trying to upgrade the Windows toolchain and libraries. This package fails to build with hdf5 1.10.5 on Windows. The cran package fails with an issue that looks like https://github.com/hhoeflin/hdf5r/issues/97:

```
*** arch - i386
cp 1_8_14/*.c 1_8_14/*.h .
/mingw32/bin/gcc  -I"C:/progra~1/R/R-testing/include" -DNDEBUG       -I/include/hdf5 -I/include/hdf5_hl -I/include/cmakeconf -I1_8_14 -I. -D__USE_MINGW_ANSI_STDIO   -O2 -Wall  -std=gnu99 -mtune=generic -c const_export.c -o const_export.o

/mingw32/bin/gcc  -I"C:/progra~1/R/R-testing/include" -DNDEBUG       -I/include/hdf5 -I/include/hdf5_hl -I/include/cmakeconf -I1_8_14 -I. -D__USE_MINGW_ANSI_STDIO   -O2 -Wall  -std=gnu99 -mtune=generic -c datatype_export.c -o datatype_ex
port.o
datatype_export.c: In function 'create_DT_H5D_mpio_no_collective_cause_t':
datatype_export.c:1471:12: error: 'H5D_MPIO_FILTERS' undeclared (first use in this function); did you mean 'H5Z_MAX_NFILTERS'?
   myenum = H5D_MPIO_FILTERS;
            ^~~~~~~~~~~~~~~~
            H5Z_MAX_NFILTERS
datatype_export.c:1471:12: note: each undeclared identifier is reported only once for each function it appears in
In file included from C:/rtools40/mingw32/lib/gcc/i686-w64-mingw32/8.3.0/include/stddef.h:1,
                 from C:/rtools40/mingw32/i686-w64-mingw32/include/inttypes.h:14,
                 from C:/rtools40/mingw32/include/H5public.h:54,
                 from C:/rtools40/mingw32/include/hdf5.h:22,
                 from global.h:23,
                 from datatype_export.h:23,
                 from datatype_export.c:20:
datatype_export.c: In function 'create_DT_H5F_info_t':
datatype_export.c:2272:41: error: 'H5F_info2_t' {aka 'struct H5F_info2_t'} has no member named 'super_ext_size'
   H5Tinsert(dtype_id, "super_ext_size", HOFFSET(H5F_info_t, super_ext_size), h5_datatype[DT_hsize_t]);
                                         ^~~~~~~
make: *** [C:/progra~1/R/R-testing/etc/i386/Makeconf:208: datatype_export.o] Error 1
ERROR: compilation failed for package 'hdf5r'

```

I also tried the Github release but that one fails even sooner:

```
*** arch - i386
/mingw32/bin/gcc  -I"C:/progra~1/R/R-testing/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c H5Error.c -o H5Error.o
In file included from H5Error.c:19:
global.h:33:10: fatal error: HelperStructs.h: No such file or directory
 #include "HelperStructs.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [C:/progra~1/R/R-testing/etc/i386/Makeconf:208: H5Error.o] Error 1
ERROR: compilation failed for package 'hdf5r'
* removing 'C:/R/library/hdf5r'
* restoring previous 'C:/R/library/hdf5r'
```

Can you please unblock us by looking into a fix?

### PR DESCRIPTION
**Pull request by jeroen**
Automatically downoad libhdf5 from [rwinlib](https://github.com/rwinlib/hdf5) at build time.

This makes it possible for any user, build server, or CI to install the source package on Windows. You never have to worry about which version of hdf5 is installed on the server.

Also cleaned up your Makevars.win and appveyor.

### CODE REVIEW

**Comment by jeroen** [comment]
OK this is done now. Passes on AppVeyor and WinBuilder: https://win-builder.r-project.org/zJElJfXkKKeM/

**Comment by hhoeflin** [comment]
Thanks!

**Comment by jeroen** [comment]
Yay. Could you maybe try to submit this to CRAN soon-ish? That would ease the transition to the new toolchain for us.

**Comment by hhoeflin** [comment]
Will try this weekend

**Comment by jeroen** [comment]
Thanks, let me know if you need any help.

**Comment by hhoeflin** [comment]
I just saw you stuck with version 1.8.16 of HDF5 instead of the newer 1.10.5. Any particular reason?

**Comment by jeroen** [comment]
I couldn't get it to work with 1.10.5, it would segfault on 32bit.

**Comment by hhoeflin** [comment]
ok, thanks. I will submit later today.

**Comment by jeroen** [comment]
Thanks. If you have time we could try to debug why it segfaults with 1.10.5 on 32bit windows, but I'm not sure if that's easy to find out. So for now this will at least improve the status quo.

**Comment by jeroen** [comment]
When you submit, it won't be auto-accepted by the bot because the UBSAN warning: https://www.stats.ox.ac.uk/pub/bdr/memtests/gcc-UBSAN/hdf5r/tests/testthat.Rout

So after you get a reply from the bot, you need to reply to the email saying that you tried to fix the UBSAN problem.

**Comment by hhoeflin** [comment]
I am trying to fix the UBSAN warnings right now
