### ISSUE TITLE
compilation error: use of undeclared identifier 'H5D_MPIO_FILTERS'

### ISSUE THREAD

**Issue by slowkow** [hhoeflin/hdf5r#97]
Could I please ask for advice to resolve the compilation error?

I previously used `hdf5r` without issues on R 3.4. I cannot recall if I had to install some additional dependencies or make some tweaks.

Recently I upgraded to 3.5.0, and now I can't install `hdf5r`. I'm on macOS 10.13.3.

```R
devtools::install_github("hhoeflin/hdf5r")
```

```
Downloading GitHub repo hhoeflin/hdf5r@master
from URL https://api.github.com/repos/hhoeflin/hdf5r/zipball/master
Installing hdf5r
'/usr/local/Cellar/r/3.5.0/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/k5/ynx90ngs6_7f7pcdkb77tp088qtqn4/T/RtmpiMaIet/devtoolsd796a405f7b/hhoeflin-hdf5r-3507499'  \
  --library='/usr/local/lib/R/3.5/site-library' --install-tests 

* installing *source* package ‘hdf5r’ ...
checking for a sed that does not truncate output... /usr/bin/sed
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking for grep that handles long lines and -e... /usr/local/bin/ggrep
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for egrep... /usr/local/bin/ggrep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for h5cc... /usr/local/bin/h5cc
checking for HDF5 libraries... yes (version 1.10.2)
checking hdf5.h usability... yes
checking hdf5.h presence... yes
checking for hdf5.h... yes
checking for H5Fcreate in -lhdf5... yes
checking for hdf5_hl.h... yes
checking for H5LTpath_valid in -lhdf5_hl... yes
checking for main in -lhdf5_hl... yes
checking for matching HDF5 Fortran wrapper... no
Found hdf5 with version: 1.10.2
checking for ggrep... /usr/local/bin/ggrep
checking whether /usr/local/bin/ggrep accepts -o... yes
checking for ggrep... (cached) /usr/local/bin/ggrep
checking whether /usr/local/bin/ggrep accepts -o... yes
configure: creating ./config.status
config.status: creating src/Makevars
** libs
cp 1_10_0/*.c 1_10_0/*.h .
clang -I"/usr/local/Cellar/r/3.5.0/lib/R/include" -DNDEBUG -I/usr/local/Cellar/hdf5/1.10.2/include -I/usr/local/opt/szip/include   -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include  -D__USE_MINGW_ANSI_STDIO -I/usr/X11/include -fPIC  -I/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home/include/darwin  -c const_export.c -o const_export.o
clang -I"/usr/local/Cellar/r/3.5.0/lib/R/include" -DNDEBUG -I/usr/local/Cellar/hdf5/1.10.2/include -I/usr/local/opt/szip/include   -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/include  -D__USE_MINGW_ANSI_STDIO -I/usr/X11/include -fPIC  -I/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home/include/darwin  -c datatype_export.c -o datatype_export.o
datatype_export.c:1530:12: error: use of undeclared identifier 'H5D_MPIO_FILTERS'
  myenum = H5D_MPIO_FILTERS;
           ^
1 error generated.
make: *** [datatype_export.o] Error 1
ERROR: compilation failed for package ‘hdf5r’
* removing ‘/usr/local/lib/R/3.5/site-library/hdf5r’
Installation failed: Command failed (1)
```

**Comment by hhoeflin** [comment]
I will try to look into it when I get the chance. Until then, when you last installed it, did you also use the same version of HDF5, i.e. 1.10.2?

Can you check if you reinstall R 3.4 if the same error occurs?

Thanks

**Comment by ryan-williams** [comment]
Seeing this issue on R 3.4; [here's my output](https://gist.github.com/ryan-williams/930640acc3af1b1ba7427ff6cbb73232)

In mine and @slowkow's above, I see:

> checking for HDF5 libraries... yes (version 1.10.2)

@hhoeflin does that answer your question about our HDF5 versions? or are you asking whether something else matches that version?

**Comment by hhoeflin** [comment]
No - that is the information I needed, thanks. Do you know if this issue also occurs for a lower version of hdf5 for you, e.g. 10.0.0?

**Comment by hhoeflin** [comment]
Thanks - they must have changed something in the internals. I will look into it next thing I get the chance, but am pretty swamped at the moment.

**Comment by majorkazer** [comment]
Hi - I am having the same issue on R3.4.4 without having ever upgraded to R3.5.0.
I am on MacOS 10.11.6

**Comment by slowkow** [comment]
@majorkazer Thanks for reporting you solution in the other issue!

Below is what seems to work for me on macOS High Sierra 10.13.3 with R 3.5.0.

```bash
wget https://cran.r-project.org/bin/macosx/el-capitan/contrib/3.5/hdf5r_1.0.0.tgz

R CMD INSTALL hdf5r_1.0.0.tgz
```

```
* installing to library ‘/usr/local/lib/R/3.5/site-library’
* installing *binary* package ‘hdf5r’ ...
* DONE (hdf5r)
```

**Comment by ambarrio** [comment]
Another report here. I am basically stuck in Linux with the same symbol in R version (R 3.4) and HDF5 version (1.10.2).

However on macOS everything works with the instruction above by @slowkow

**Comment by ccasar** [comment]
Ran into the same problem on Manjaro/Arch Linux with R 3.5.0 downgrading from hdf5 1.10.2-3 to 1.10.1-1 solved the issue for me.

**Comment by mjsteinbaugh** [comment]
I'm running into the same issue on CentOS as well, using conda r-base 3.4.1, gcc 4.8.5, hdf5 1.10.2.

**Comment by mjsteinbaugh** [comment]
Can confirm that this will build with hdf5 1.10.1 on CentOS -- the 1.10.2 update seems to break.

**Comment by dburkhardt** [comment]
Would just like to give this issue another bump. We're using hdf5 1.10.2-3. Would be great if this latest version were supported. Until then we will downgrade HDF5.

**Comment by scottgigante** [comment]
For anyone trying to install without downgrading the system HDF5, this worked on Arch Linux:
1. Install HDF5 from source to `/usr/local/hdf5_legacy` (or your own chosen path)
2. Install `hdf5r` from source:
```
git clone https://github.com/hhoeflin/hdf5r
cd hdf5r
./configure --with-hdf5="/usr/local/hdf5_legacy/bin/h5cc"
LD_LIBRARY_PATH=/usr/local/hdf5_legacy/lib/ R CMD INSTALL --no-configure .
```
3. Add the local HDF5 install path to R's LD_LIBRARY_PATH by editing `$(R RHOME)/etc/ldpaths`

**Comment by lambdamoses** [comment]
I switched to hdf5 1.8.20_1 with homebrew, but then when I ran `devtools::install_github(repo = 'hhoeflin/hdf5r')`, I got

    configure: error: The version of hdf5 installed on your system is not sufficient. Please ensure that at least version 1.8.13 is installed
I know that the version is sufficient, so something must be wrong.

**Comment by lambdamoses** [comment]
I successfully installed hdf5 1.10.1 from source, and tried to install hdf5r the way of @scottgigante did. I got the exact same problem @slowkow got on MacOS, R 3.5.1. I do need to install the development version so I can't get the one from CRAN, so what to do?

    Error: package or namespace load failed for ‘hdf5r’ in dyn.load(file, DLLpath = DLLpath, ...):
     unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/hdf5r/libs/hdf5r.so':
      dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/hdf5r/libs/hdf5r.so, 6): Symbol not found: _H5P_CLS_ATTRIBUTE_CREATE_ID_g
      Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/hdf5r/libs/hdf5r.so
      Expected in: flat namespace
     in /Library/Frameworks/R.framework/Versions/3.5/Resources/library/hdf5r/libs/hdf5r.so

**Comment by oldoldjiang** [comment]
I also got the same issue on my Ubuntu. I've fixed it by just deleting the anaconda folder, which also contain several hdf5 lib files.

**Comment by jkanche** [comment]
Have the same error on Arch linux. I've tried @scottgigante solution but still have the same issue.

**Comment by jkanche** [comment]
A solution that worked for me is installing the fake-hdf5r package. This only works if you are not dealing with any hdf5 format files but need this package for seurat or something else  - 

https://github.com/UCSF-TI/fake-hdf5r

**Comment by dg13** [comment]
I'm on OSX 10.13.6, R-3.5.1, had the same problem. Installing hdf5 with homebrew didn't seem to work, so I tried manually compiling and installing hdf5 1.10.1 from source:
wget https://support.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.10.1.tar.bz2
tar -jxvf hdf5-1.10.1.tar.bz2
cd hdf5-1.10.1
./configure --prefix=/usr/local/opt/hdf5
make
make install
Then in R I do:
install.packages("hdf5r",configure.args="--with-hdf5=/usr/local/opt/hdf5/bin/h5cc")

**Comment by hhoeflin** [comment]
Please have a look at the newest commit on master. It should hopefully fix the problem. Sorry for the long wait - lots to do at work ...

**Comment by hhoeflin** [comment]
Hi,

whoops. I did not realize the same issue occurs for 1.10.2. I only
implmeneted for 1.10.3. Will fix later tonight. If you try 1.10.3, it
should work.

**Comment by attilagk** [comment]
Hi, installing from the *hdf5_1_10_3* branch works but installing from *master* still fails due to the compilation error related to `H5D_MPIO_FILTERS`.  Please merge *hdf5_1_10_3* into *master*.  Thanks.

**Comment by hhoeflin** [comment]
yes - thanks. I haven't done the pull request yet. Let me fix the rest
tonight on the branch, then I will merge the branch.

**Comment by hhoeflin** [comment]
Have another try. Should be fixed now.

**Comment by scottgigante** [comment]
Works on Arch Linux, 1.10.2. Thanks!
