### ISSUE TITLE
Fails to build on centos7.3.1611 with hdf5 1.12.0 from install the hdf5r of R package

### ISSUE THREAD

**Issue by honghh2018** [hhoeflin/hdf5r#164]
Hi @hhoeflin ,
      Thanks for develop great tools for R.
       But i got a issue make me crazy when i try to install the hdf5r package using the latest hdf5 version of 1.12.0.
       I try everything i could, but it still get error, and can not be install the hdf5r.
      
       The install code like:install.packages("hdf5r", configure.args="--with-hdf5=/share/nas1/Data/Users/honghh/temp/JAGS/hdf5r_compiled/bin/h5cc")
      The system was Centos 7.3.1611 
      The gcc version was 7.3.0 and the old gcc was 4.8.5
       I build the hdf5-1.12.0.tar source by hand ,the build code like below:
     ./configure --prefix=/share/nas1/Data/Users/honghh/temp/JAGS/hdf5r_compiled --enable-fortran --enable-fortran --enable-java
   make -j 16
   make install
  The error information showing below:
   cp 1_12_0/*.c 1_12_0/*.h .
gcc -I"/share/nas1/Data/software/R/R-4.0.2/lib64/R/include" -DNDEBUG   -I/usr/local/include/  -D__USE_MINGW_ANSI_STDIO -DH5_USE_110_API  -fpic  -g -O2  -c const_export.c -o const_export.o
In file included from global.h:33:0,
                 from const_export.h:22,
                 from const_export.c:23:
HelperStructs.h:33:3: error: unknown type name ‘H5O_token_t’
   H5O_token_t token;
   ^~~~~~~~~~~
HelperStructs.h:81:3: error: unknown type name ‘H5L_info1_t’
   H5L_info1_t link;
   ^~~~~~~~~~~
const_export.c: In function ‘show_all_const_data_frame’:
const_export.c:73:73: error: ‘H5F_ACC_SWMR_WRITE’ undeclared (first use in this function); did you mean ‘CONST_H5F_ACC_SWMR_WRIT’?
   ((long long *) REAL(R_const))[CONST_H5F_ACC_SWMR_WRITE] = (long long) H5F_ACC_SWMR_WRITE;
                                                                         ^~~~~~~~~~~~~~~~~~
                                                                         CONST_H5F_ACC_SWMR_WRITE
const_export.c:73:73: note: each undeclared identifier is reported only once for each function it appears in
const_export.c:77:72: error: ‘H5F_ACC_SWMR_READ’ undeclared (first use in this function); did you mean ‘H5F_ACC_SWMR_WRITE’?
   ((long long *) REAL(R_const))[CONST_H5F_ACC_SWMR_READ] = (long long) H5F_ACC_SWMR_READ;
                                                                        ^~~~~~~~~~~~~~~~~
                                                                        H5F_ACC_SWMR_WRITE
const_export.c:273:69: error: ‘H5O_INFO_BASIC’ undeclared (first use in this function); did you mean ‘CONST_H5O_INFO_BASIC’?
   ((long long *) REAL(R_const))[CONST_H5O_INFO_BASIC] = (long long) H5O_INFO_BASIC;

  and the R was 4.0.2
  The R session showing below:
![image](https://user-images.githubusercontent.com/41668708/107374881-0eb98a00-6b23-11eb-859e-36e7739d7b1e.png)

   I get stuck on this error all day long, i hope you can help me to get rid of this issue.
   Best,
   hanhuihong

**Comment by hhoeflin** [comment]
My first guess would be that you did not set "LD_LIBRARY_PATH" and "LIBRARY_PATH". 

In general I would recommend for you to use a tool like spack:

https://github.com/spack/spack

to install hdf5 and activate it. It lets you have several hdf5 versions side by side and also solves a lot of other installation problems. With it you will not very often have to install things from source by hand. Hope this helps.

**Comment by honghh2018** [comment]
Thanks the well advice @hhoeflin, it was really helpful.
 I had already install the hdf5 through spack,but it still get error. so i want to try again using the LD_LIBRARY_PATH and LIBRARY_PATH that you posted.
  But i was  confused  which path i should be take for LIBARARY_PATH and LD_LIBRARY_PATH as below hdf5 software.
  
![image](https://user-images.githubusercontent.com/41668708/107601377-7d9cfd00-6c61-11eb-9a52-0e1c4230f7ab.png)
  the hdf5 directory structure like below:
   
![image](https://user-images.githubusercontent.com/41668708/107601474-d10f4b00-6c61-11eb-96f1-25442cf6ffe8.png)

  I guess that:
  LD_LIBRARY_PATH=/share/nas1/Data/Users/honghh/temp/JAGS/hdf5r_compiled/lib/:${LD_LIBRARY_PATH}
  LIBRARY_PATH=/share/nas1/Data/Users/honghh/temp/JAGS/hdf5r_compiled/include:${LIBRARY_PATH}
  how can i set this env ? and can above post be right?
  Any advice would be appreciated
  Best,
  Hanhuihong

**Comment by hhoeflin** [comment]
So I just tried it with spack on CentOS7 and it worked without issues. Here is what I did:

```
spack install hdf5@1.12.0+hl
spack load hdf5@1.12.0+hl
```

Then open R and install hdf5r in it.

For the `LD_LIBRARY_PATH` and the `LIBRARY_PATH`, the subdirectory is <HDF5PATH>/lib
If you load the package with spack, these paths are automatically being set.

Hope this works for you.
